[package]
name = "proguard"
version = "3.0.0"
authors = ["Sentry <oss@sentry.io>"]
keywords = ["proguard", "retrace"]
description = "Basic proguard mapping file handling for Rust"
repository = "https://github.com/getsentry/sentry-rust"
homepage = "https://sentry.io/welcome/"
license = "BSD-3-Clause"
readme = "README.md"
edition = "2018"

[dependencies]
uuid = { version = "0.8.1", features = ["v5"], optional = true }

[dev-dependencies]
lazy_static = "1.4.0"
