[package]
name = "proguard"
version = "2.0.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
keywords = ["proguard", "retrace"]
description = "Basic proguard mapping file handling for Rust"
homepage = "https://github.com/mitsuhiko/proguard"
documentation = "https://docs.rs/proguard"
license = "BSD-3-Clause"
readme = "README.md"
edition = "2018"

[dependencies]
regex = "1.1.0"
memmap = "0.7.0"
lazy_static = "1.2.0"
uuid = { version = "0.8.1", features = ["v5"] }
